services:
    vending-machine-db:
        image: postgres:14-alpine
        restart: always
        container_name: vending-machine-db
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=root
            - POSTGRES_DB=postgres
        ports:
            - "5432:5432"
        networks:
            - custom_network
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U root -d postgres" ]
            interval: 30s
            timeout: 10s
            retries: 5

    liquibase:
        image: liquibase/liquibase
        container_name: liquibase
        depends_on:
            vending-machine-db:
                condition: service_healthy
        volumes:
            - ./changelog:/liquibase/changelog
            - ./liquibase.properties:/liquibase/liquibase.properties
        environment:
            - LIQUIBASE_COMMAND_URL=jdbc:postgresql://vending-machine-db:5432/postgres
            - LIQUIBASE_COMMAND_USERNAME=root
            - LIQUIBASE_COMMAND_PASSWORD=password
        command: ["--defaults-file=/liquibase/liquibase.properties", "update"]
        networks:
            - custom_network

    vending-machine:
        image: vending-machine:latest
        container_name: vending-machine
        ports:
            - "8087:8087"
        environment:
            - SPRING_APPLICATION_NAME=vending-machine
            - SPRING_R2DBC_URL=r2dbc:postgresql://vending-machine-db:5432/postgres
            - SPRING_R2DBC_USERNAME=root
            - SPRING_R2DBC_PASSWORD=password
        depends_on:
            vending-machine-db:
                condition: service_healthy
        networks:
            - custom_network


    pg-admin:
        image: dpage/pgadmin4
        container_name: pg-admin
        restart: no
        environment:
            - PGADMIN_DEFAULT_EMAIL=user@domain.com
            - PGADMIN_DEFAULT_PASSWORD=password
        ports:
            - "5050:80"
        networks:
            - custom_network

networks:
    custom_network:
        driver: bridge

volumes:
    postgres_data:
        driver: local